name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Deploying Script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          REPO_URL="https://github.com/${{ github.repository }}.git"
          if [ ! -d "${{ secrets.SSH_PROJECT_DIR }}" ]; then
            mkdir -p ${{ secrets.SSH_PROJECT_DIR }}
            git clone $REPO_URL ${{ secrets.SSH_PROJECT_DIR }}
          elif [ ! -d "${{ secrets.SSH_PROJECT_DIR }}/.git" ]; then
            git clone $REPO_URL ${{ secrets.SSH_PROJECT_DIR }}
          else
            cd ${{ secrets.SSH_PROJECT_DIR }}
            git fetch origin master
            git reset --hard origin/master
          fi
